FROM ubuntu:latest
MAINTAINER Justin Zimmer "jzimmer@leasehawk.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 4295
ENTRYPOINT ["python"]
CMD ["application.py"]
