FROM amazon/aws-eb-python:3.4.2-onbuild-3.5.1
MAINTAINER Justin Zimmer <jzimmer@leasehawk.com>

# RUN apk add --no-cache py2-pip \
#     && pip install --upgrade pip \
#     && pip install flask \
#     && pip install -r /tmp/requirements.txt

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 4295
ENTRYPOINT ["python"]
CMD ["application.py"]